name: Turkce Hutbeleri Guncelle

on:
  schedule:
    - cron: '30 18 * * 4' # Her Perşembe TSİ 21:30
    - cron: '0 5 * * 5'  # Her Cuma TSİ 08:00
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Paketleri Yükle
        run: pip install requests beautifulsoup4 urllib3

      - name: Scraper'ı Çalıştır
        run: python scraper.py

      - name: Dosyayı Otomatik Commit ve Push Yap
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update: Turkce hutbeler guncellendi"
          file_pattern: 'hutbeler.json'
